"""Convert JSON metric files into LaTeX tables auto-included in the paper.

Reads:
  results/metrics/<model>_<dataset>.json    — probe accuracy
  results/metrics/phase1_*.json             — Phase 1 experiments
  results/metrics/phase2_*.json             — Phase 2 robustness checks

Writes:
  paper/tables/auto_*.tex   — \input-able LaTeX tables that match the paper
"""
import json, os, sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
METRICS = BASE / "results" / "metrics"
OUT = BASE / "paper" / "tables"
OUT.mkdir(parents=True, exist_ok=True)


def load(name):
    p = METRICS / name
    return json.load(open(p)) if p.exists() else None


def fmt(v, prec=3):
    if v is None: return "—"
    if isinstance(v, float):
        return f"{v:.{prec}f}"
    return str(v)


def write_table(filename, body):
    (OUT / filename).write_text(body)
    print(f"  wrote {filename} ({len(body)} chars)")


# ============================================================
# Table 1: per-model probe accuracy (in-domain)
# ============================================================
def table_probe_acc():
    rows = []
    for model in ["Llama-3.1-8B-Instruct", "Mistral-7B-Instruct-v0.3",
                  "Qwen3-8B", "gemma-2-9b-it"]:
        for ds in ["cicids2017", "unsw_nb15"]:
            d = load(f"{model}_{ds}.json")
            if d is None: continue
            rows.append({
                "model": model.replace("_", "\\_"),
                "ds": ds,
                "best_layer": d.get("best_layer"),
                "known_acc": d.get("known_accuracy"),
                "known_auroc": d.get("known_auroc"),
                "holdout_acc": d.get("holdout_accuracy"),
                "holdout_auroc": d.get("holdout_auroc"),
                "gap_acc": d.get("known_accuracy", 0) - d.get("holdout_accuracy", 0),
            })

    out = ["% auto-generated by scripts/build_paper_tables.py"]
    out.append("\\begin{tabular}{lccccc}")
    out.append("\\toprule")
    out.append("Model & Dataset & best L & known acc & holdout acc & gap \\\\")
    out.append("\\midrule")
    for r in rows:
        ds_short = "CIC-2017" if r["ds"] == "cicids2017" else "UNSW"
        out.append(f"{r['model'][:28]} & {ds_short} & {r['best_layer']} & "
                   f"{fmt(r['known_acc'])} & {fmt(r['holdout_acc'])} & "
                   f"{r['gap_acc']:+.3f} \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_probe_acc.tex", "\n".join(out) + "\n")


# ============================================================
# Table: V1 TF-IDF baseline
# ============================================================
def table_tfidf():
    d = load("phase1_expC_tfidf_baseline.json")
    if d is None:
        print("  skip TF-IDF (not done yet)"); return
    out = ["% TF-IDF baseline auto"]
    out.append("\\begin{tabular}{lcccccc}")
    out.append("\\toprule")
    out.append("Vectorizer & \\multicolumn{3}{c}{CIC-IDS2017} & \\multicolumn{3}{c}{UNSW-NB15} \\\\")
    out.append("\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}")
    out.append("           & known & holdout & gap & known & holdout & gap \\\\")
    out.append("\\midrule")
    for vec in ["word_unigrams_bigrams", "char_3to5"]:
        c = d["cicids2017"][vec]
        u = d["unsw_nb15"][vec]
        nice = "word $1$--$2$g" if vec == "word_unigrams_bigrams" else "char $3$--$5$g"
        out.append(f"TF-IDF {nice} & "
                   f"{fmt(c['known_accuracy'])} & {fmt(c['holdout_accuracy'])} & "
                   f"{c['gap_acc']:+.3f} & "
                   f"{fmt(u['known_accuracy'])} & {fmt(u['holdout_accuracy'])} & "
                   f"{u['gap_acc']:+.3f} \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_tfidf.tex", "\n".join(out) + "\n")


# ============================================================
# Table: V4 zero-shot transfer
# ============================================================
def table_zero_shot():
    d = load("phase2_zero_shot_transfer.json")
    if d is None:
        print("  skip zero-shot (not done yet)"); return
    out = ["% V4 zero-shot transfer auto"]
    out.append("\\begin{tabular}{lcccccc}")
    out.append("\\toprule")
    out.append(" & \\multicolumn{2}{c}{CIC-2018 (same schema)} & "
               "\\multicolumn{2}{c}{IoT-23} & \\multicolumn{2}{c}{CTU-13} \\\\")
    out.append("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}")
    out.append("Model & in-dom & cic2017$\\to$ & in-dom & cic2017$\\to$ & in-dom & cic2017$\\to$ \\\\")
    out.append("\\midrule")
    for model, dd in d.items():
        cells = [model.replace("_", "\\_")]
        for ds in ["cicids2018", "iot23", "ctu13"]:
            if ds not in dd: continue
            r = dd[ds]
            in_dom = max(v["in_domain_probe_auroc"] for v in r["per_layer"].values())
            best_t = max(v["cicids2017_dir_auroc"] for v in r["per_layer"].values())
            cells.append(fmt(in_dom))
            cells.append(fmt(best_t))
        out.append(" & ".join(cells) + " \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_zero_shot.tex", "\n".join(out) + "\n")


# ============================================================
# Table: V2 sparse decomposition R^2
# ============================================================
def table_sparse():
    d = load("phase2_b1_sparse_decomp.json")
    if d is None:
        print("  skip sparse decomp (not done yet)"); return
    out = ["% V2 sparse decomp R^2 auto"]
    out.append("\\begin{tabular}{llcccc}")
    out.append("\\toprule")
    out.append("Model & Dataset & $R^2$(all) & $R^2$($k{=}1$) & $R^2$($k{=}3$) & top-1 axis \\\\")
    out.append("\\midrule")
    for m in d:
        for ds, r in d[m].items():
            keys = list(r["greedy_topk"].keys())
            k1 = "1" if "1" in keys else 1
            k3 = "3" if "3" in keys else 3
            top1 = r["greedy_topk"][k1]["features"][0].replace("_", "\\_")
            out.append(f"{m.replace('_', chr(92)+'_')} & {ds.replace('_', chr(92)+'_')} & "
                       f"{fmt(r['r2_with_all'])} & {fmt(r['greedy_topk'][k1]['r2'])} & "
                       f"{fmt(r['greedy_topk'][k3]['r2'])} & \\texttt{{{top1[:25]}}} \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_sparse.tex", "\n".join(out) + "\n")


# ============================================================
# Table: A4 multi-seed
# ============================================================
def table_multi_seed():
    d = load("phase2_a4_multi_seed.json")
    if d is None:
        print("  skip multi-seed (not done yet)"); return
    out = ["% Multi-seed std auto"]
    out.append("\\begin{tabular}{lccccc}")
    out.append("\\toprule")
    out.append("Model & Dataset & known mean & holdout mean & gap mean & gap std \\\\")
    out.append("\\midrule")
    for m, dd in d["summary"].items():
        for ds, s in dd.items():
            out.append(f"{m.replace('_', chr(92)+'_')} & {ds.replace('_', chr(92)+'_')} & "
                       f"{fmt(s['known_acc_mean'])} $\\pm$ {fmt(s['known_acc_std'], 4)} & "
                       f"{fmt(s['holdout_acc_mean'])} $\\pm$ {fmt(s['holdout_acc_std'], 4)} & "
                       f"{s['gap_mean']:+.3f} & {fmt(s['gap_std'], 4)} \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_multi_seed.tex", "\n".join(out) + "\n")


# ============================================================
# Table: A2 multi-probe
# ============================================================
def table_multi_probe():
    d = load("phase2_a2_multi_probe.json")
    if d is None:
        print("  skip multi-probe (not done yet)"); return
    out = ["% Multi-probe auto"]
    out.append("\\begin{tabular}{llcccc}")
    out.append("\\toprule")
    out.append("Model & Dataset & LR gap & LDA gap & PCA-LR gap & MLP gap \\\\")
    out.append("\\midrule")
    for m in d:
        for ds, dd in d[m].items():
            row_cells = [m.replace("_", "\\_"), ds.replace("_", "\\_")]
            for p in ["lr", "lda", "pca_lr", "mlp"]:
                if p in dd:
                    row_cells.append(f"{dd[p]['gap_acc']:+.3f}")
                else:
                    row_cells.append("—")
            out.append(" & ".join(row_cells) + " \\\\")
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    write_table("auto_multi_probe.tex", "\n".join(out) + "\n")


def main():
    print("Building paper tables from results/metrics/ ...")
    table_probe_acc()
    table_tfidf()
    table_zero_shot()
    table_sparse()
    table_multi_seed()
    table_multi_probe()
    print(f"\nAll tables written to {OUT}/")


if __name__ == "__main__":
    main()
